#! /bin/sh

# disabling laptop keyboard
xinput float 16

#autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &

# gtk themes and term colorsheme

# polybar
~/.config/polybar/launch.sh &

# eww sidebar
#eww open bar --config ~/.config/eww/bar

#global settings
#bspc config automatic_scheme alternate
#bspc config initial_polarity second_child
#bspc config pointer_modifier lock
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner
#bspc config remove_disabled_monitors true
#bspc config remove_unplugged_monitors true
#bspc config merge_overlapping_monitors true


# workspaces
displayport="$(xrandr --query | grep -o "HDMI-1 connected" | cut -d " " -f 1)"
if [ -n "$displayport" ]; then
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor LVDS-1 -d 6 7
    #xrandr --output LVDS-1 --off --output HDMI-1 --primary --mode 1366x768 --pos 0x0 -- rotate normal
    bash ~/.screenlayout/display_profile.sh
else
    bspc monitor LVDS-1 -d 1 2 3 4 5
    bash ~/.screenlayout/normal_profile.sh
fi
#bash ~/.config/bspwm/auto_switch.sh &

bspc config focus_follows_pointer true

bspc config top_padding 40
#36
#bspc config right_padding 50

# borders
bspc config focused_border_color "#949494"
#797d85
bspc config normal_border_color "#373a3b"
bspc config border_width  2
bspc config borderless_monocle true
#gaps
bspc config gapless_monocle false
bspc config window_gap 6
bspc config split_ratio 0.50

bspc rule -a Brave-browser desktop='^2'
bspc rule -a audacity desktop='^4'
bspc rule -a Gimp-2.10 desktop='^4'
bspc rule -a Inkscape desktop='^4'
bspc rule -a steam desktop='^5'
bspc rule -a discord desktop='^5'
bspc rule -a notion-app desktop='^3'
bspc rule -a zoom desktop='^5' state=floating follow=on
bspc rule -a Microsoft-edge desktop='^5'
bspc rule -a Nemo state=floating follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Rofi state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a File-roller state=floating
bspc rule -a Wihotspot-gui state=floating
bspc rule -a "Picture in picture" state=floating
pgrep bspswallow || bspswallow &

#feh --no-fehbg --bg-fill ~/Downloads/anime_gril\ 1.jpeg
feh --no-fehbg --bg-fill ~/Images/wallpapers/joker.jpg
killall picom
picom
wihotspot-gui
kitty
